name: WakaTime REAME

on:
    schedule:
        # 12点运行此文件
        - cron: '30 18 * * *'
    workflow_dispatch:

jobs:
    update-readme:
        name: Update Readme through waka
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
              with: 
                WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
